name: Deploy to GitHub Pages

on:
  # Runs when screener updates results
  push:
    branches:
      - main
    paths:
      - 'results/screener_results.json'
      - 'public/**'
  # Allows manual trigger
  workflow_dispatch:

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        # v3 -> v4
        uses: actions/checkout@v4 
      
      - name: Setup Pages
        # v3 -> v4
        uses: actions/configure-pages@v4 
      
      - name: Upload artifact
        # v2 -> v3 (가장 핵심적인 변경)
        uses: actions/upload-pages-artifact@v3 
        with:
          # Upload public directory
          path: './public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        # v2 -> v4
        uses: actions/deploy-pages@v4
